

"""template models

Revision ID: e28c48d06652
Revises: 
Create Date: 2024-12-23 18:32:33.973050

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28c48d06652'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('template_elements',
    sa.Column('element_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('element_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_index(op.f('ix_template_elements_template_id'), 'template_elements', ['template_id'], unique=False)
    op.create_index('template_element_templates_id_order_idx', 'template_elements', ['template_id', 'order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('template_element_templates_id_order_idx', table_name='template_elements')
    op.drop_index(op.f('ix_template_elements_template_id'), table_name='template_elements')
    op.drop_table('template_elements')
    op.drop_table('templates')
    # ### end Alembic commands ###
