"""tables with right struct and indices

Revision ID: eb8d7a381f5a
Revises: 
Create Date: 2025-10-19 23:00:33.570877

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

import labstructanalyzer

# revision identifiers, used by Alembic.
revision: str = 'eb8d7a381f5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('is_draft', sa.Boolean(), nullable=False),
                    sa.Column('max_score', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reports',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('template_id', sa.Uuid(), nullable=False),
                    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', labstructanalyzer.domain.report_status.ReportStatusType(), nullable=False),
                    sa.Column('grader_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('reports_author_id_template_id_created_at_idx', 'reports',
                    ['author_id', 'template_id', 'created_at'], unique=False)
    op.create_table('template_elements',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('template_id', sa.Uuid(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('properties', sa.JSON(), nullable=True),
                    sa.Column('parent_element_id', sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_template_id', 'template_elements', ['template_id', 'id'], unique=False)
    op.create_index('idx_template_type', 'template_elements', ['template_id', 'type'], unique=False)
    op.create_index(op.f('ix_template_elements_template_id'), 'template_elements', ['template_id'], unique=False)
    op.create_index('template_element_templates_id_order_idx', 'template_elements', ['template_id', 'order'],
                    unique=False)
    op.create_table('answers',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('report_id', sa.Uuid(), nullable=False),
                    sa.Column('element_id', sa.Uuid(), nullable=False),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.Column('pre_grade', sa.JSON(), nullable=True),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['element_id'], ['template_elements.id'], ),
                    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_answers_element_id'), 'answers', ['element_id'], unique=False)
    op.create_index(op.f('ix_answers_report_id'), 'answers', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_report_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_element_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('template_element_templates_id_order_idx', table_name='template_elements')
    op.drop_index(op.f('ix_template_elements_template_id'), table_name='template_elements')
    op.drop_index('idx_template_type', table_name='template_elements')
    op.drop_index('idx_template_id', table_name='template_elements')
    op.drop_table('template_elements')
    op.drop_index('reports_author_id_template_id_created_at_idx', table_name='reports')
    op.drop_table('reports')
    op.drop_table('templates')
    # ### end Alembic commands ###
